// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtXqk_uaeSG80tcSlekConNZkP6hOZCPs',
    appId: '1:136925704339:web:f18acc24eb3b94b0eb1d66',
    messagingSenderId: '136925704339',
    projectId: 'groceryapp-aac6a',
    authDomain: 'groceryapp-aac6a.firebaseapp.com',
    storageBucket: 'groceryapp-aac6a.appspot.com',
    measurementId: 'G-ZDRFPT6HME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Usg3S8J-RGKU0r2ezSXOU_-xTE9vucs',
    appId: '1:136925704339:android:3b42891f1333fe52eb1d66',
    messagingSenderId: '136925704339',
    projectId: 'groceryapp-aac6a',
    storageBucket: 'groceryapp-aac6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7gv39GBvgKNWxwKPi1EHHD_SyT3hU3bk',
    appId: '1:136925704339:ios:e7ba851f33ff69deeb1d66',
    messagingSenderId: '136925704339',
    projectId: 'groceryapp-aac6a',
    storageBucket: 'groceryapp-aac6a.appspot.com',
    iosClientId: '136925704339-71pph19qch90hnrfh29tu3k14ujq7qq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.userGrocerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7gv39GBvgKNWxwKPi1EHHD_SyT3hU3bk',
    appId: '1:136925704339:ios:e7ba851f33ff69deeb1d66',
    messagingSenderId: '136925704339',
    projectId: 'groceryapp-aac6a',
    storageBucket: 'groceryapp-aac6a.appspot.com',
    iosClientId: '136925704339-71pph19qch90hnrfh29tu3k14ujq7qq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.userGrocerapp',
  );
}
